#!/bin/sh -e

# To address security bug #363580, but don't change them again and
# again if local admin put something else.
if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt 2.0.2-2; then
 chmod 640 /etc/wordpress/config* >/dev/null 2>&1 || true
 chgrp www-data /etc/wordpress/config* >/dev/null 2>&1 || true
fi

#DEBHELPER#

exit 0
